launch_config:
  renderer: RaytracedLighting
  headless: false
env_url: ''
working_area_size:
- 4
- 4
- 3
rt_subframes: 4
num_frames: 10
num_cameras: 2
disable_render_products_between_captures: false
simulation_duration_between_captures: 0.0
resolution:
- 640
- 640
camera_look_at_target_offset: 0.55
camera_distance_to_target_min_max:
  - 5.00
  - 10.00
writer_type: CocoWriter
writer_kwargs:
  output_dir: "_out_obj_based_sdg_coco"
  image_output_format: "jpg"
  coco_categories:
    sm_angle: { name: "sm_angle", id: 1, supercategory: "part", isthing: 1 }
labeled_assets_and_properties:
- url: omniverse://localhost/Library/Horvath etalv Datasets/SM_Angle.usd
  label: sm_angle
  count: 10
  floating: true
  scale_min_max:
  - 0.35
  - 1.35
shape_distractors_types:
- capsule
- cone
- cylinder
- sphere
- cube
shape_distractors_scale_min_max:
  - 0.015
  - 0.15
shape_distractors_num: 350
mesh_distractors_urls:
- /Isaac/Environments/Simple_Warehouse/Props/SM_CardBoxD_04_1847.usd
- /Isaac/Environments/Simple_Warehouse/Props/SM_CardBoxA_01_414.usd
- /Isaac/Environments/Simple_Warehouse/Props/S_TrafficCone.usd
- /Isaac/Environments/Simple_Warehouse/Props/S_WetFloorSign.usd
- /Isaac/Environments/Simple_Warehouse/Props/SM_BarelPlastic_B_03.usd
- /Isaac/Environments/Office/Props/SM_Board.usd
- /Isaac/Environments/Office/Props/SM_Book_03.usd
- /Isaac/Environments/Office/Props/SM_Book_34.usd
- /Isaac/Environments/Office/Props/SM_BookOpen_01.usd
- /Isaac/Environments/Office/Props/SM_Briefcase.usd
- /Isaac/Environments/Office/Props/SM_Extinguisher.usd
- /Isaac/Environments/Hospital/Props/SM_GasCart_01b.usd
- /Isaac/Environments/Hospital/Props/SM_MedicalBag_01a.usd
- /Isaac/Environments/Hospital/Props/SM_MedicalBox_01g.usd
- /Isaac/Environments/Hospital/Props/SM_Toweldispenser_01a.usd
mesh_distractors_scale_min_max:
  - 0.35
  - 1.35
mesh_distractors_num: 75