launch_config:
  renderer: RaytracedLighting
  headless: false
env_url: ''
working_area_size:
- 5
- 5
- 1
rt_subframes: 50
num_frames: 10
num_cameras: 1
disable_render_products_between_captures: false
simulation_duration_between_captures: 0.15
resolution:
- 720
- 720
camera_look_at_target_offset: 0.10
camera_distance_to_target_min_max:
  - 5.00
  - 10.00
labeled_assets_and_properties:
- url: "omniverse://localhost/Library/Datasets/SM_Angle.usd"
  label: "sm_angle"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35
- url: "omniverse://localhost/Library/Datasets/SM_ballstem.usd"
  label: "sm_ballstem"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_Bilincs_Bilincs_003.usd"
  label: "sm_bilincs_bilincs_003"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_body.usd"
  label: "sm_body"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_Bonnet.usd"
  label: "sm_bonnet"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_Erveg2.usd"
  label: "sm_erveg2"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_handle.usd"
  label: "sm_handle"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_Pipe_Clamp_25.usd"
  label: "sm_pipe_clamp_25"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_Rightangle2.usd"
  label: "sm_rightangle2"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Datasets/SM_seat.usd"
  label: "sm_seat"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

writer_type: CocoWriter
writer_kwargs:
  output_dir: "coco_physX"
  image_output_format: "jpg"
  semantic_types: ["class"]
  coco_categories:
    sm_angle:
      name: "sm_angle"
      id: 1
      supercategory: "part"
      isthing: 1
      color: [255, 0, 0]   # <- add a 3-element RGB list
    sm_ballstem:
      name: "sm_ballstem"
      id: 2
      supercategory: "part"
      isthing: 1
      color: [0, 255, 0]
    sm_bilincs_bilincs_003:
      name: "sm_bilincs_bilincs_003"
      id: 3
      supercategory: "part"
      isthing: 1
      color: [0, 0, 255]
    sm_body:
      name: "sm_body"
      id: 4
      supercategory: "part"
      isthing: 1
      color: [255, 255, 0]

    sm_bonnet:
      name: "sm_bonnet"
      id: 5
      supercategory: "part"
      isthing: 1
      color: [255, 0, 255]

    sm_erveg2:
      name: "sm_erveg2"
      id: 6
      supercategory: "part"
      isthing: 1
      color: [0, 255, 255]

    sm_handle:
      name: "sm_handle"
      id: 7
      supercategory: "part"
      isthing: 1
      color: [255, 128, 0]

    sm_pipe_clamp_25:
      name: "sm_pipe_clamp_25"
      id: 8
      supercategory: "part"
      isthing: 1
      color: [128, 0, 255]

    sm_rightangle2:
      name: "sm_rightangle2"
      id: 9
      supercategory: "part"
      isthing: 1
      color: [64, 192, 64]

    sm_seat:
      name: "sm_seat"
      id: 10
      supercategory: "part"
      isthing: 1
      color: [192, 64, 64]
yolo_split_ratio: 0.8
yolo_split_seed: null
yolo_output_dir: "yolo_out"
shape_distractors_types:
- capsule
- cone
- cylinder
- sphere
- cube
shape_distractors_scale_min_max:
  - 0.015
  - 0.15
shape_distractors_num: 10
mesh_distractors_urls:
- omniverse://localhost/Library/Distractors/0.usdc
- omniverse://localhost/Library/Distractors/1.usdc
- omniverse://localhost/Library/Distractors/2.usdc
- omniverse://localhost/Library/Distractors/3.usdc
- omniverse://localhost/Library/Distractors/6.usdc
- omniverse://localhost/Library/Distractors/7.usdc
- omniverse://localhost/Library/Distractors/8.usdc
- omniverse://localhost/Library/Distractors/9.usdc
mesh_distractors_scale_min_max:
  - 0.35
  - 1.35
mesh_distractors_num: 30

floor_mdl_materials:
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Masonry/Facade_Brick_Red_Clinker.mdl"
    subidentifier: "Facade_Brick_Red_Clinker" 
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Mesh/Metal_Mesh_Weave_03.mdl"
    subidentifier: "Metal_Mesh_Weave_03"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Mesh/Metal_Mesh_Weave_02.mdl"
    subidentifier: "Metal_Mesh_Weave_02"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Mesh/Metal_Mesh_Weave_01.mdl"
    subidentifier: "Metal_Mesh_Weave_01"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Aluminum_Knurling.mdl"
    subidentifier: "Aluminum_Knurling"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Copper_Knurling.mdl"
    subidentifier: "Copper_Knurling"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Plaster/Facade_Plaster_Rough.mdl"
    subidentifier: "Facade_Plaster_Rough"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Plaster/Mosaic_Multi_Color_Stone.mdl"
    subidentifier: "Mosaic_Multi_Color_Stone"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paper/Cardboard.mdl"
    subidentifier: "Cardboard"

asset_mdl_materials:
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Copper_Brushed.mdl"
    subidentifier: "Copper_Brushed"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Composite/Carbon_Fiber.mdl"
    subidentifier: "Carbon_Fiber"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Aluminum_Anodized.mdl"
    subidentifier: "Aluminum_Anodized"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Carpaint/Carpaint_Candy.mdl"
    subidentifier: "Carpaint_Candy"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Steel_Painted.mdl"
    subidentifier: "Steel_Painted"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Chalk_Paint_Pebbles.mdl"
    subidentifier: "Chalk_Paint_Pebbles"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Carpaint/Effect_Pigment_Metallic.mdl"
    subidentifier: "Effect_Pigment_Metallic"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Carpaint/Carpaint_Metallic.mdl"
    subidentifier: "Carpaint_Metallic"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Chromium.mdl"
    subidentifier: "Chromium"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Aluminum_Knurling.mdl"
    subidentifier: "Aluminum_Knurling"
