launch_config:
  renderer: RaytracedLighting
  headless: true
env_url: ''
working_area_size:
- 5
- 5
- 1
rt_subframes: 32
num_frames: 1000
num_cameras: 4
disable_render_products_between_captures: false
simulation_duration_between_captures: 0.15
resolution:
- 720
- 720
camera_look_at_target_offset: 0.10
camera_distance_to_target_min_max:
  - 12.00
  - 16.00
labeled_assets_and_properties:
- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_Rightangle2.usd"
  label: "angle_bracket"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35
- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_ballstem.usd"
  label: "ballstem"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_Bilincs_Bilincs_003.usd"
  label: "u_bracket"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_body.usd"
  label: "body"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_Bonnet.usd"
  label: "bonnet"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_Erveg2.usd"
  label: "cable_shoe"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_handle.usd"
  label: "handle"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_Pipe_Clamp_25.usd"
  label: "pipe_clamp"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_Angle.usd"
  label: "l_bracket"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

- url: "omniverse://localhost/Library/Roboforge_collections/Datasets/SM_seat.usd"
  label: "seat"
  count: 3
  floating: true
  scale_min_max:
  - 0.85
  - 1.35

writer_type: CocoWriter
writer_kwargs:
  output_dir: "coco_out"
  image_output_format: "jpg"
  semantic_types: ["class"]
  coco_categories:
    l_bracket:
      name: "l_bracket"
      id: 1
      supercategory: "part"
      isthing: 1
      color: [255, 0, 0]  
    u_bracket:
      name: "u_bracket"
      id: 2
      supercategory: "part"
      isthing: 1
      color: [0, 0, 255]
    angle_bracket:
      name: "angle_bracket"
      id: 3
      supercategory: "part"
      isthing: 1
      color: [64, 192, 64]
    seat:
      name: "seat"
      id: 4
      supercategory: "part"
      isthing: 1
      color: [192, 64, 64]
    pipe_clamp:
      name: "pipe_clamp"
      id: 5
      supercategory: "part"
      isthing: 1
      color: [128, 0, 255]
    handle:
      name: "handle"
      id: 6
      supercategory: "part"
      isthing: 1
      color: [255, 128, 0]
    bonnet:
      name: "bonnet"
      id: 7
      supercategory: "part"
      isthing: 1
      color: [255, 0, 255]
    body:
      name: "body"
      id: 8
      supercategory: "part"
      isthing: 1
      color: [255, 255, 0]
    ballstem:
      name: "ballstem"
      id: 9
      supercategory: "part"
      isthing: 1
      color: [0, 255, 0]
    cable_shoe:
      name: "cable_shoe"
      id: 10
      supercategory: "part"
      isthing: 1
      color: [0, 255, 255]
yolo_split_ratio: 0.8
yolo_split_seed: null
yolo_output_dir: "E:/Arjun/Ablation Study/yolo_out"

shape_distractors_scale_min_max:
  - 0.015
  - 0.15
shape_distractors_num: 2
mesh_distractors_urls:
- omniverse://localhost/Library/Roboforge_collections/Distractors/0.usdc
- omniverse://localhost/Library/Roboforge_collections/Distractors/1.usdc
- omniverse://localhost/Library/Roboforge_collections/Distractors/2.usdc
- omniverse://localhost/Library/Roboforge_collections/Distractors/3.usdc
- omniverse://localhost/Library/Roboforge_collections/Distractors/6.usdc
- omniverse://localhost/Library/Roboforge_collections/Distractors/7.usdc
- omniverse://localhost/Library/Roboforge_collections/Distractors/8.usdc
- omniverse://localhost/Library/Roboforge_collections/Distractors/9.usdc
mesh_distractors_scale_min_max:
  - 0.35
  - 1.35
mesh_distractors_num: 10

floor_mdl_materials:
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Masonry/Facade_Brick_Red_Clinker.mdl"
    subidentifier: "Facade_Brick_Red_Clinker" 
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Leather/ABS_Quilted_Leather.mdl"
    subidentifier: "ABS_Quilted_Leather"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Aluminum_Knurling.mdl"
    subidentifier: "Aluminum_Knurling"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Copper_Knurling.mdl"
    subidentifier: "Copper_Knurling"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Plaster/Facade_Plaster_Rough.mdl"
    subidentifier: "Facade_Plaster_Rough"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Plaster/Mosaic_Multi_Color_Stone.mdl"
    subidentifier: "Mosaic_Multi_Color_Stone"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paper/Cardboard.mdl"
    subidentifier: "Cardboard"

asset_mdl_materials:
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Hammer_Paint.mdl"
    subidentifier: "Hammer_Paint"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Wood/Wood_Tiles_Poplar_Multicolor.mdl"
    subidentifier: "Wood_Tiles_Poplar_Multicolor"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Aluminum_Anodized.mdl"
    subidentifier: "Aluminum_Anodized"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Carpaint/Carpaint_Candy.mdl"
    subidentifier: "Carpaint_Candy"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Steel_Painted.mdl"
    subidentifier: "Steel_Painted"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Chalk_Paint_Pebbles.mdl"
    subidentifier: "Chalk_Paint_Pebbles"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Wood/Wood_Tiles_Walnut_Multicolor.mdl"
    subidentifier: "Wood_Tiles_Walnut_Multicolor"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Paint/Carpaint/Carpaint_Metallic.mdl"
    subidentifier: "Carpaint_Metallic"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Ground/Ground_Hard_Court.mdl"
    subidentifier: "Ground_Hard_Court"
  - mdl_url: "omniverse://localhost/NVIDIA/Materials/vMaterials_2/Metal/Aluminum_Knurling.mdl"
    subidentifier: "Aluminum_Knurling"